services:
  zulip_admin:
    build: .
    container_name: django-docker
    expose:
      - 8000
#
#    volumes:
#      - .:/app
#    networks:
#      traefik:

    labels: # new
      - "traefik.enable=true"
      - "traefik.http.routers.django.entrypoints=https"
      - "traefik.http.routers.django.rule=Host(`zadm.kik-soft.ru`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsEncrypt"
      #- "traefik.http.services.bdjangoot-service.loadbalancer.server.port=80"
#  zulip_listen:
#    build:
#      context: . #/app
#      dockerfile: Dockerfile_z_l
#    volumes:
#      - .:/app
#    expose:
#      - 80
#    labels:
#      - "traefik.enable=true"
#networks:
#  traefik:
#    name: traefik
#    external: true