# Generated by Django 5.1.6 on 2025-07-03 12:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('tg_id', models.IntegerField()),
                ('zulip_channel_id', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_type', models.CharField(choices=[('staff', 'Сотрудник'), ('client', 'Клиент'), ('anonim', 'Аноним'), ('admin', 'Админ')], default='client', max_length=10)),
                ('pin_code', models.IntegerField()),
                ('activated', models.BooleanField(default=True)),
            ],
        ),
    ]
