# Generated by Django 5.1.6 on 2025-07-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='pin_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='zulip_channel_id',
            field=models.IntegerField(default=0),
        ),
    ]
