# Generated by Django 5.1.6 on 2025-07-03 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_company_client_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_msg_at',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(default='Новая компания', max_length=50),
        ),
    ]
