# Generated by Django 5.2.4 on 2025-07-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_last_msg_at_alter_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='last_msg_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
